name: game_template
description: A mobile game built in Flutter.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: '>=2.19.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  audioplayers: ^3.0.0
  cupertino_icons: ^1.0.2
  go_router: ^6.0.1
  logging: ^1.1.0
  provider: ^6.0.2
  shared_preferences: ^2.0.13
  flutter_svg: ^2.0.5
  flutter_colorpicker: ^1.0.3
  http: ^0.13.5
  path_provider: ^2.0.14
  flutter_pdfview: ^1.3.0

  # If you don't need one of the following dependencies,
  # delete the relevant line below, and get rid of any Dart code
  # that references the dependency.
  firebase_core: ^2.1.1  # Needed for Crashlytics below
  firebase_crashlytics: ^3.0.3  # Error reporting
  games_services: ^3.0.0  # Achievements and leaderboards
  google_mobile_ads: ^2.0.1  # Ads
  in_app_purchase: ^3.0.1  # In-app purchases

dev_dependencies:
  analysis_defaults:
    path: ../analysis_defaults
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.12.0
  test: ^1.19.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/music/
    - assets/sfx/
    - assets/time_to_party_assets/

  fonts:
    - family: Permanent Marker
      fonts:
        - asset: assets/Permanent_Marker/PermanentMarker-Regular.ttf
    - family: HindMadurai
      fonts:
        - asset: assets/fonts/HindMadurai-Bold.ttf
          weight: 700

